spring.application.name=ProductMicroservice

server.port=8081
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#ждём ответ всех/минимум от одной синхронизированных реплик (min.insync.replicas=2)
spring.kafka.producer.acks=all

#Так делать можно, но не рекомендуется
#spring.kafka.producer.retries=10
#spring.kafka.producer.properties.retry.backoff.ms=1000

#Время накапливания батча
spring.kafka.producer.properties.linger.ms=0

#максимальное время которое мы ждём для получения ответа от брокеров одного ответа
spring.kafka.producer.properties.request.timeout.ms=5000

#Общее время на повторы
spring.kafka.producer.properties.delivery.timeout.ms=10000

#Идемпотенция - записать в партицию топика что-либо только один раз, и при повторной отправке оно не запишется снова
spring.kafka.producer.properties.enable.idempotence=true

#Сколько сообщений в "полёте" могут быть без ответа
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5



spring.kafka.producer.properties.spring.json.type.mapping=createProductEvent:ru.khalov.tests.core.CreateProductEvent

